version: "3"
services:
  web:
    image: node-authentication-cognito-demo
    build: .
    command: "node server.js"
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
